import type { Service, Therapist } from "@/types/database";

export const fallbackServices: Service[] = [
  {
    id: "fallback-service-1",
    name: "Luxury Facial",
    category: "Facial",
    description: "A transformative 90-minute ritual using rare botanical extracts and 24K gold leaf infusions.",
    duration_minutes: 90,
    price: 4500,
    image_url: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&q=80",
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-service-2",
    name: "Aromatherapy Massage",
    category: "Massage",
    description: "Drift into bliss with our master blend of essential oils, designed for total renewal.",
    duration_minutes: 75,
    price: 3800,
    image_url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80",
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-service-3",
    name: "Hot Stone Therapy",
    category: "Therapy",
    description: "Volcanic basalt stones heated to perfection melt tension and restore inner balance.",
    duration_minutes: 120,
    price: 5200,
    image_url: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80",
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-service-4",
    name: "Royal Ayurvedic Ceremony",
    category: "Ritual",
    description: "Five-thousand year old healing science meets modern luxury in this immersive ceremony.",
    duration_minutes: 150,
    price: 6000,
    image_url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80",
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-service-5",
    name: "Hair Spa Ritual",
    category: "Hair",
    description: "Nourish your crown with organic protein treatments and scalp revitalisation techniques.",
    duration_minutes: 60,
    price: 2800,
    image_url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-service-6",
    name: "Deep Tissue Massage",
    category: "Massage",
    description: "Precision therapeutic techniques that reach the deepest layers of muscle and fascia.",
    duration_minutes: 90,
    price: 4200,
    image_url: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&q=80",
    is_active: true,
    created_at: null,
  },
];

export const fallbackTherapists: Therapist[] = [
  {
    id: "fallback-therapist-1",
    name: "Riya Kapoor",
    specialty: "Ayurvedic & Facial",
    experience_years: 8,
    bio: "Certified in Kerala Ayurveda and advanced facial techniques. Trained in Bali and Japan.",
    avatar_url: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    rating: 4.9,
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-therapist-2",
    name: "Priya Nair",
    specialty: "Hot Stone & Deep Tissue",
    experience_years: 6,
    bio: "Expert in therapeutic massage with specialisation in sports recovery and deep tissue work.",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    rating: 4.8,
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-therapist-3",
    name: "Ananya Singh",
    specialty: "Aromatherapy & Wellness",
    experience_years: 10,
    bio: "Senior therapist trained in Paris and Switzerland. Specialist in holistic wellness rituals.",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
    rating: 5,
    is_active: true,
    created_at: null,
  },
  {
    id: "fallback-therapist-4",
    name: "Meera Iyer",
    specialty: "Hair & Scalp Rituals",
    experience_years: 5,
    bio: "Hair restoration specialist with expertise in Ayurvedic scalp treatments and organic care.",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&h=100&fit=crop&crop=face",
    rating: 4.7,
    is_active: true,
    created_at: null,
  },
];
